#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "Updating Ubuntu mirrors for Kamatera install" | log
officialDomain="archive.ubuntu.com" | log
mirrorDomain="mirror.${CWM_ZONE,,}.kamatera.com" | log 
officialFullDomain="http:\/\/archive.ubuntu.com\/ubuntu" | log
officialMirrors="mirror:\/\/mirrors.ubuntu.com\/mirrors.txt" | log

echo "mirrorDomain : $mirrorDomain"
echo "officialFullDomain : $officialFullDomain"
echo "officialMirrors : $officialMirrors"

#backupFile /etc/apt/sources.list
#kamateraMirrors=$(sed -n 's/'"${officialDomain}"'/'"${mirrorDomain}"'/gp' /etc/apt/sources.list) | log 
#ubuntuMirrors=$(sed 's/'"${officialFullDomain}"'/'"${officialMirrors}"'/g' /etc/apt/sources.list) | log
#echo -e "#Kamatera Mirrors (1st priority)\n$kamateraMirrors\n\n$ubuntuMirrors" > /etc/apt/sources.list | log

#apt update | log

tagScript success

exit 0
